//Create a function that takes two numbers and returns the larger number.

function number(num){
    if( num1 > num2){
        console.log(num1)
    }
    else{
        console.log(num2)
    }
}
let num1 = Number(prompt("Enter first Number:"))
let num2 = Number(prompt("Enter Second Number:"))


//

function idk (hello){
    let idk2 = hello.split()
    let idk3 = idk2.reverse()
    let result = idk3.join()
    console.log(result)
}
idk("Hello")

//

function qwerty(num){
    for (let i = 1; i <= num;i++){
        if(i%2!==0){
            console.log(i)
        }
    }
}

qwerty(34)

//

function func(words){
    let idkk = words.toUpperCase()
    console.log(idkk)
}
